# Generated by Django 5.0.2 on 2024-02-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_team_task_employee_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_visits", models.IntegerField(default=0)),
            ],
        ),
    ]
