# Generated by Django 5.0.2 on 2024-02-15 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="productivity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
