# Generated by Django 5.0.2 on 2024-02-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_team_productivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("Developer", "dev"),
                    ("Project Manager", "pm"),
                    ("QA", "qa"),
                    ("Designer", "designer"),
                    ("DevOps", "devops"),
                ],
                max_length=20,
            ),
        ),
    ]
